# general settings
name: dataset1
model_type: EDVRModel
scale: 4

manual_seed: 10

# dataset and data loader settings
datasets:
  val:
    name: XRAY
    type: XrayVideoTestDatasetSTF
    flag: grayscale
    dataroot_gt: [../data/dataset1/HR]
    dataroot_lq: [../data/dataset1/LR]
    io_backend:
      type: disk

    cache_data: false
    num_frame: 3
    num_frame_hi: 2
    gt_size: [400,1024,450]
    padding: reflection_circle

# network structures
network_g:
  num_in_ch: 1
  num_out_ch: 1
  num_feat: 128
  num_frame: 3
  num_frame_hi: 2
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 40
  center_frame_idx: ~
  hr_in: false
  with_predeblur: false
  with_tsa: true

# path
path:
  pretrain_network_g: conda/XFusion/xfusion/model/model_stf_xray_poisson.pth
  strict_load_g: true
  resume_state: ~
